In [ ]:

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from matplotlib.colors import ListedColormap
import seaborn as sns
from sklearn.datasets import make_blobs, make_classification, make_moons
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score, mean_absolute_error, mean_squared_error
from scipy.spatial.distance import cosine
import pandas as pd
import time

In [17]:
df = pd.read_csv('ToyotaCorolla.csv')
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   str
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   str
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   str
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), str(3)
memory usage: 437.7 KB

Index(['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'CC', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Parking_Assistant', 'Tow_Bar'],
      dtype='str')

In [20]:

df.describe()

,Id,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
mean,721.555014,10730.824513,55.947075,5.548747,1999.625348,68533.259749,101.502089,0.674791,0.055710,1576.85585,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,3626.964585,18.599988,3.354085,1.540722,37506.448872,14.981080,0.468616,0.229441,424.38677,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,4350.000000,1.000000,1.000000,1998.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,8450.000000,44.000000,3.000000,1998.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,9900.000000,61.000000,5.000000,1999.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,11950.000000,70.000000,8.000000,2001.000000,87020.750000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,32500.000000,80.000000,12.000000,2004.000000,243000.000000,192.000000,1.000000,1.000000,16000.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [33]:
df.columns.notna()
df.isnull().sum()

Id                   0
Model                0
Price                0
Age_08_04            0
Mfg_Month            0
Mfg_Year             0
KM                   0
Fuel_Type            0
HP                   0
Met_Color            0
Color                0
Automatic            0
CC                   0
Doors                0
Cylinders            0
Gears                0
Quarterly_Tax        0
Weight               0
Mfr_Guarantee        0
BOVAG_Guarantee      0
Guarantee_Period     0
ABS                  0
Airbag_1             0
Airbag_2             0
Airco                0
Automatic_airco      0
Boardcomputer        0
CD_Player            0
Central_Lock         0
Powered_Windows      0
Power_Steering       0
Radio                0
Mistlamps            0
Sport_Model          0
Backseat_Divider     0
Metallic_Rim         0
Radio_cassette       0
Parking_Assistant    0
Tow_Bar              0
dtype: int64

In [22]:
df.head(5)

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0

In [38]:

cols = df.select_dtypes(include=['int64', 'float64']).columns
corr_mat = df[cols].corr()
print(corr_mat)

                         Id     Price  Age_08_04  Mfg_Month  Mfg_Year  \
Id                 1.000000 -0.738250   0.906132   0.043742 -0.919523
Price             -0.738250  1.000000  -0.876590  -0.018138  0.885159
Age_08_04          0.906132 -0.876590   1.000000  -0.123255 -0.983661
Mfg_Month          0.043742 -0.018138  -0.123255   1.000000 -0.057416
Mfg_Year          -0.919523  0.885159  -0.983661  -0.057416  1.000000
KM                 0.273298 -0.569960   0.505672  -0.020630 -0.504974
HP                -0.109375  0.314990  -0.156622  -0.039312  0.164697
Met_Color         -0.079713  0.108905  -0.108150   0.030266  0.103310
Automatic          0.066265  0.033081   0.031717   0.009146 -0.033567
CC                -0.117704  0.126389  -0.098084   0.037387  0.091892
Doors             -0.130207  0.185326  -0.148359  -0.012069  0.151442
Cylinders               NaN       NaN        NaN        NaN       NaN
Gears             -0.043343  0.063104  -0.005364  -0.013063  0.007766
Quarterly_Tax     -0.240821  0.219197  -0.198431   0.031373  0.193934
Weight            -0.414500  0.581198  -0.470253  -0.002167  0.473478
Mfr_Guarantee     -0.162006  0.197802  -0.164658  -0.005771  0.166697
BOVAG_Guarantee   -0.015065  0.028133   0.006865  -0.003863 -0.006206
Guarantee_Period  -0.086256  0.146627  -0.152563   0.029010  0.148218
ABS               -0.461437  0.306138  -0.412887   0.072532  0.402215
Airbag_1          -0.123465  0.093588  -0.105406   0.003756  0.105359
Airbag_2          -0.358316  0.248974  -0.329017   0.076749  0.317075
Airco             -0.386207  0.429259  -0.403600   0.057088  0.395674
Automatic_airco   -0.327468  0.588262  -0.426259  -0.049017  0.437718
Boardcomputer     -0.695207  0.601292  -0.719449   0.017715  0.720567
CD_Player         -0.464520  0.481374  -0.510895  -0.016736  0.517008
Central_Lock      -0.238940  0.343458  -0.279631   0.010055  0.279490
Powered_Windows   -0.236723  0.356518  -0.283856   0.025185  0.280996
Power_Steering    -0.091587  0.064275  -0.069192  -0.055495  0.079676
Radio             -0.010971 -0.041887   0.013791   0.031601 -0.019607
Mistlamps         -0.139708  0.222083  -0.126895  -0.033504  0.133737
Sport_Model       -0.028704  0.164121  -0.110988   0.052789  0.102080
Backseat_Divider  -0.136398  0.102569  -0.116751   0.023245  0.113237
Metallic_Rim      -0.022232  0.108564  -0.040045   0.023506  0.036022
Radio_cassette    -0.011611 -0.043179   0.012857   0.032576 -0.018844
Parking_Assistant -0.049103  0.044375  -0.048172   0.007113  0.047171
Tow_Bar            0.159171 -0.172369   0.188720  -0.042170 -0.182206

                         KM        HP  Met_Color  Automatic        CC  ...  \
Id                 0.273298 -0.109375  -0.079713   0.066265 -0.117704  ...
Price             -0.569960  0.314990   0.108905   0.033081  0.126389  ...
Age_08_04          0.505672 -0.156622  -0.108150   0.031717 -0.098084  ...
Mfg_Month         -0.020630 -0.039312   0.030266   0.009146  0.037387  ...
Mfg_Year          -0.504974  0.164697   0.103310  -0.033567  0.091892  ...
KM                 1.000000 -0.333538  -0.080503  -0.081854  0.102683  ...
HP                -0.333538  1.000000   0.058712   0.013144  0.035856  ...
Met_Color         -0.080503  0.058712   1.000000  -0.019335  0.031812  ...
Automatic         -0.081854  0.013144  -0.019335   1.000000  0.066740  ...
CC                 0.102683  0.035856   0.031812   0.066740  1.000000  ...
Doors             -0.036197  0.092424   0.085243  -0.027654  0.079903  ...
Cylinders               NaN       NaN        NaN        NaN       NaN  ...
Gears              0.015023  0.209477   0.018601  -0.098555  0.014629  ...
Quarterly_Tax      0.278165 -0.298432   0.011326  -0.055371  0.306996  ...
Weight            -0.028598  0.089614   0.057929   0.057249  0.335637  ...
Mfr_Guarantee     -0.212851  0.140026   0.154850   0.026194 -0.057407  ...
BOVAG_Guarantee    0.001438  0.022701   0.010783   0.023393 -0.081725  ...
Guarantee_Period  -0.138942  0.076163   0.009295  -0.002256 -0.017683  ...
ABS               -0.177203  0.057832   0.022298  -0.016128  0.037806  ...
Airbag_1          -0.018012  0.025137   0.100055  -0.011895  0.022678  ...
Airbag_2          -0.139275  0.017644   0.038416   0.001171  0.024738  ...
Airco             -0.133057  0.241134   0.114190  -0.028353  0.119888  ...
Automatic_airco   -0.258221  0.244957   0.027977   0.059057  0.162669  ...
Boardcomputer     -0.353862  0.129715   0.089886  -0.037069  0.009312  ...
CD_Player         -0.266826  0.102300   0.198220  -0.010967  0.057787  ...
Central_Lock      -0.125177  0.250122   0.153307  -0.002502  0.072634  ...
Powered_Windows   -0.156242  0.265593   0.145147  -0.005864  0.055299  ...
Power_Steering     0.007397  0.048850   0.086544  -0.004469  0.032933  ...
Radio              0.013661  0.020998   0.072756  -0.014600 -0.000361  ...
Mistlamps         -0.074327  0.210571   0.023821   0.003077  0.017326  ...
Sport_Model       -0.044784 -0.006027   0.003779   0.013175 -0.035195  ...
Backseat_Divider  -0.045658  0.010908   0.037741  -0.018876 -0.055711  ...
Metallic_Rim      -0.013599  0.206784   0.053829  -0.078095  0.003236  ...
Radio_cassette     0.015770  0.019919   0.071530  -0.014150 -0.000470  ...
Parking_Assistant -0.064318  0.029990   0.036691   0.159985  0.002883  ...
Tow_Bar            0.084153  0.068271   0.148536   0.018786  0.002725  ...

                   Powered_Windows  Power_Steering     Radio  Mistlamps  \
Id                       -0.236723       -0.091587 -0.010971  -0.139708
Price                     0.356518        0.064275 -0.041887   0.222083
Age_08_04                -0.283856       -0.069192  0.013791  -0.126895
Mfg_Month                 0.025185       -0.055495  0.031601  -0.033504
Mfg_Year                  0.280996        0.079676 -0.019607   0.133737
KM                       -0.156242        0.007397  0.013661  -0.074327
HP                        0.265593        0.048850  0.020998   0.210571
Met_Color                 0.145147        0.086544  0.072756   0.023821
Automatic                -0.005864       -0.004469 -0.014600   0.003077
CC                        0.055299        0.032933 -0.000361   0.017326
Doors                     0.107626        0.059792 -0.008318   0.064705
Cylinders                      NaN             NaN       NaN        NaN
Gears                     0.131423        0.021200  0.015090   0.238789
Quarterly_Tax             0.003827        0.047956 -0.031816   0.024024
Weight                    0.213356        0.047849 -0.038407   0.135236
Mfr_Guarantee             0.041551        0.029771 -0.052058   0.083958
BOVAG_Guarantee          -0.012406        0.164392 -0.039075   0.117472
Guarantee_Period          0.040534       -0.118974  0.198886  -0.118021
ABS                       0.099465        0.254626 -0.054670   0.179433
Airbag_1                  0.121641        0.561770 -0.010035   0.092618
Airbag_2                  0.049129        0.212187 -0.223663   0.228843
Airco                     0.543982        0.096893 -0.030571   0.466751
Automatic_airco           0.203687        0.036912 -0.092647   0.312141
Boardcomputer             0.213327        0.087207 -0.129094   0.147900
CD_Player                 0.195386        0.068452 -0.185568   0.124589
Central_Lock              0.875552        0.129646 -0.011251   0.487426
Powered_Windows           1.000000        0.123458 -0.035811   0.496697
Power_Steering            0.123458        1.000000  0.009075   0.077985
Radio                    -0.035811        0.009075  1.000000  -0.126118
Mistlamps                 0.496697        0.077985 -0.126118   1.000000
Sport_Model              -0.000650        0.098866 -0.137729   0.004342
Backseat_Divider          0.078244        0.265169 -0.209590   0.245463
Metallic_Rim              0.291419        0.053217 -0.034162   0.412545
Radio_cassette           -0.037626       -0.004584  0.991621  -0.134245
Parking_Assistant        -0.006602        0.007979  0.015520  -0.000842
Tow_Bar                  -0.013252        0.030453  0.143652  -0.069479

                   Sport_Model  Backseat_Divider  Metallic_Rim  \
Id                   -0.028704         -0.136398     -0.022232
Price                 0.164121          0.102569      0.108564
Age_08_04            -0.110988         -0.116751     -0.040045
Mfg_Month             0.052789          0.023245      0.023506
Mfg_Year              0.102080          0.113237      0.036022
KM                   -0.044784         -0.045658     -0.013599
HP                   -0.006027          0.010908      0.206784
Met_Color             0.003779          0.037741      0.053829
Automatic             0.013175         -0.018876     -0.078095
CC                   -0.035195         -0.055711      0.003236
Doors                -0.129881         -0.022542     -0.039555
Cylinders                  NaN               NaN           NaN
Gears                 0.174117          0.076705      0.295077
Quarterly_Tax         0.067525          0.198419     -0.011965
Weight                0.125974          0.036446      0.053847
Mfr_Guarantee         0.054129          0.256249      0.026728
BOVAG_Guarantee       0.173978          0.457468      0.060434
Guarantee_Period     -0.172874         -0.484427     -0.044003
ABS                   0.200596          0.256659      0.079152
Airbag_1              0.113671          0.307947      0.057345
Airbag_2              0.300274          0.589987      0.075128
Airco                 0.002730          0.105149      0.233166
Automatic_airco       0.215287          0.018756      0.100363
Boardcomputer         0.036802          0.287615     -0.024999
CD_Player             0.057920          0.148806      0.044730
Central_Lock         -0.003128          0.058449      0.281334
Powered_Windows      -0.000650          0.078244      0.291419
Power_Steering        0.098866          0.265169      0.053217
Radio                -0.137729         -0.209590     -0.034162
Mistlamps             0.004342          0.245463      0.412545
Sport_Model           1.000000          0.357713      0.051810
Backseat_Divider      0.357713          1.000000      0.104862
Metallic_Rim          0.051810          0.104862      1.000000
Radio_cassette       -0.136708         -0.206390     -0.033228
Parking_Assistant    -0.005782         -0.002537     -0.026816
Tow_Bar              -0.094147         -0.049176     -0.037331

                   Radio_cassette  Parking_Assistant   Tow_Bar
Id                      -0.011611          -0.049103  0.159171
Price                   -0.043179           0.044375 -0.172369
Age_08_04                0.012857          -0.048172  0.188720
Mfg_Month                0.032576           0.007113 -0.042170
Mfg_Year                -0.018844           0.047171 -0.182206
KM                       0.015770          -0.064318  0.084153
HP                       0.019919           0.029990  0.068271
Met_Color                0.071530           0.036691  0.148536
Automatic               -0.014150           0.159985  0.018786
CC                      -0.000470           0.002883  0.002725
Doors                   -0.008265           0.025893  0.102292
Cylinders                     NaN                NaN       NaN
Gears                    0.015397          -0.007422 -0.029357
Quarterly_Tax           -0.031009          -0.019118 -0.004988
Weight                  -0.037265           0.027660 -0.074932
Mfr_Guarantee           -0.054532          -0.017140 -0.023328
BOVAG_Guarantee         -0.039827           0.018050 -0.006718
Guarantee_Period         0.193910           0.025189  0.008590
ABS                     -0.055724           0.025317 -0.065976
Airbag_1                -0.022117           0.009174  0.052312
Airbag_2                -0.220917           0.003207 -0.063956
Airco                   -0.036524           0.051976 -0.024362
Automatic_airco         -0.092348           0.044350 -0.117967
Boardcomputer           -0.128073           0.052803 -0.128001
CD_Player               -0.189668           0.035973 -0.079911
Central_Lock            -0.016954           0.018196 -0.007728
Powered_Windows         -0.037626          -0.006602 -0.013252
Power_Steering          -0.004584           0.007979  0.030453
Radio                    0.991621           0.015520  0.143652
Mistlamps               -0.134245          -0.000842 -0.069479
Sport_Model             -0.136708          -0.005782 -0.094147
Backseat_Divider        -0.206390          -0.002537 -0.049176
Metallic_Rim            -0.033228          -0.026816 -0.037331
Radio_cassette           1.000000           0.015655  0.140753
Parking_Assistant        0.015655           1.000000  0.026210
Tow_Bar                  0.140753           0.026210  1.000000

[36 rows x 36 columns]

In [87]:


X_prep = df.drop(columns=['Price'])
y = df['Price']

X = pd.get_dummies(X_prep)  
print(X.shape)
X.head(5)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=101)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(pd.DataFrame(X_train_scaled, columns=X.columns).head())

(1436, 367)
         Id  Age_08_04  Mfg_Month  Mfg_Year        KM        HP  Met_Color  \
0  0.859648   0.801440   1.330222 -1.050497  1.801230 -1.899713  -1.432896
1  0.217683   0.581437  -1.059598 -0.387876  0.050992  0.561985  -1.432896
2  1.441504   1.296447  -1.358325 -1.050497 -0.050269  0.561985   0.697887
3  0.039760   0.251432   0.732767 -0.387876  0.366678  0.561985   0.697887
4 -0.958051  -0.848584  -0.462143  0.937367 -0.974231  0.561985   0.697887

   Automatic        CC     Doors  ...  Color_Beige  Color_Black  Color_Blue  \
0  -0.242983  0.899516  1.010021  ...    -0.041776    -0.384708   -0.497821
1  -0.242983  0.040998  1.010021  ...    -0.041776    -0.384708   -0.497821
2  -0.242983  0.040998  1.010021  ...    -0.041776    -0.384708    2.008753
3  -0.242983  0.040998 -1.096253  ...    -0.041776    -0.384708   -0.497821
4   4.115519  0.040998  1.010021  ...    -0.041776    -0.384708   -0.497821

   Color_Green  Color_Grey  Color_Red  Color_Silver  Color_Violet  \
0    -0.429798   -0.515472  -0.489633     -0.302084     -0.051187
1    -0.429798    1.939970  -0.489633     -0.302084     -0.051187
2    -0.429798   -0.515472  -0.489633     -0.302084     -0.051187
3    -0.429798   -0.515472   2.042345     -0.302084     -0.051187
4    -0.429798   -0.515472  -0.489633      3.310337     -0.051187

   Color_White  Color_Yellow
0     6.443487     -0.041776
1    -0.155195     -0.041776
2    -0.155195     -0.041776
3    -0.155195     -0.041776
4    -0.155195     -0.041776

[5 rows x 367 columns]

Я разделил выборку в соотношениии 80-20 (тренировка-тест). Чтобы все категориальные признаки приняли числовое значение, я воспользовался get_dummies , а дальше спокойно разделил сплитом и заскейлил по опыту прошлого дз.  

На тренировочной выборке модель ищет закономерности на основании правильных ответов, а вот на обучающей она проходит тест, учиться применять свои навыки. Если бы она тестировалась, на то что учила, то  она просто подставляла бы знакомые ей ответы, без прокачки "мозга"

In [85]:
#from sklearn.linear_model import LinearRegression, Ridge, Lasso
#from sklearn.metrics import accuracy_score, confusion_matrix, r2_score, mean_absolute_error, mean_squared_error
lnreg = LinearRegression()
start = time.time()
lnreg.fit(X_train_scaled, y_train)
end = time.time()
t_time = end - start
y_pred = lnreg.predict(X_test_scaled)
print(mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred))
print(f"{time} секунд")

2083040.226400411 970.1025917331463 0.869904863098901
<module 'time' (built-in)> секунд

In [81]:
import time
from sklearn.model_selection import GridSearchCV
sl = {'alpha' : [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0] }
rid2 = Ridge()
rid_search = GridSearchCV(
    rid2, #оптимизируем модель
    sl,
    scoring='r2',
    n_jobs=-1
)
start_time = time.time()
rid_search.fit(X_train_scaled, y_train)
end_time = time.time()
t_time = end_time - start_time
 

print(f"Лучшие параметры: {rid_search.best_params_}")
print(f"Лучшая точность на CV: {rid_search.best_score_:.4f}")
print(f"Точность на тесте: {rid_search.score(X_test_scaled, y_test):.4f}")
print(f"Время обучения: {t_time:.4f} секунд")

Лучшие параметры: {'alpha': 100.0}
Лучшая точность на CV: 0.8860
Точность на тесте: 0.8746
Время обучения: 0.2152 секунд

In [82]:
rid = Ridge(alpha=100)
rid.fit(X_train_scaled, y_train)
y_pred = rid.predict(X_test_scaled)
print(mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred))

2007413.256557915 894.6403782509931 0.8746281040955843

In [83]:
from sklearn.model_selection import GridSearchCV
import time
sl = {'alpha' : [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0] }
las2 = Lasso()
las_search = GridSearchCV(
    las2, #оптимизируем модель
    sl,
    scoring='r2',
    n_jobs=-1
)
start_time = time.time()
las_search.fit(X_train_scaled, y_train) 
end_time = time.time()
t_time = end_time - start_time


print(f"Лучшие параметры: {las_search.best_params_}")
print(f"Лучшая точность на CV: {las_search.best_score_:.4f}")
print(f"Точность на тесте: {las_search.score(X_test_scaled, y_test):.4f}")
print(f"Время обучения: {t_time:.4f} секунд")

Лучшие параметры: {'alpha': 10.0}
Лучшая точность на CV: 0.8875
Точность на тесте: 0.9100
Время обучения: 1.0041 секунд

In [84]:
las = Lasso(alpha=10)

las.fit(X_train_scaled, y_train)

y_pred = las.predict(X_test_scaled)
print(mean_squared_error(y_test, y_pred), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred))

1441658.7564973517 814.155542325459 0.9099619916532813

Использовалось аналитическое решение, для оценки качества решения использовались MSE, MAE, R^2

Скорость обучения у LAsso в пять раз больше Ridge (1.0, 0.2 секунд), потому что Lasso имеет итеративный алгоритм , а Ridge аналитический. Но при этом у Лассо работает более качественно. Для достижения максимальноц точности у моделей использовался подбор с помощью GridSearchCV